### PR TITLE
[CS-3012] Notification icon on android

### PR DESCRIPTION
**Pull request by oidoug**
### Description

Added new assets for notification icon on android.

- [x] Completes #(CS-3012)

### Checklist

- [x] All UI changes have been tested on a small device

### Screenshots

Screenshot

Screenshot

### CODE REVIEW

**Review by danibonilha — COMMENTED** [review]
I think we already have this asset as `ic_launcher_foreground`, you can check this [PR](https://github.com/cardstack/cardwallet/pull/553/files) to make sure, at the time I just added `ic_launcher` on `com.google.firebase.messaging.default_notification_icon` bc notifications were not implemented yet, I find odd that it didn't work, maybe it doesn't accept a `xml`, but looking at[ firebase's docs](https://github.com/firebase/quickstart-android/tree/master/messaging#custom-default-icon) it seems if we remove this property it should take the icon launcher as default, maybe we can try that and see how it goes.

**Comment by oidoug** [comment]
@danibonilha, you're right, if we don't set any resource it builds it using ic_launcher, with foreground and background.

I'm pushing an update soon.

One thing we need to keep an open eye, notifications on android are taking a lot longer to arrive.

**Review by topwebtek7 — APPROVED** [review]
LGTM! 👍🏼

**Review by danibonilha — APPROVED** [review]
Thanks for looking into it! 🚢

**Pull request merged**
