### PR TITLE
fix: undefined id on transaction sections hook

### PR DESCRIPTION
**Pull request by eshinkawa**
### Description
Getting a null pointer because of the transaction id

### Screenshots

Sep-07-2021 23-27-29

https://user-images.githubusercontent.com/8547776/132438288-cdb444d8-da6a-4415-9fa5-fc9f4364e4a9.mp4

### CODE REVIEW

**Review by topwebtek7 — APPROVED** [review]
Looks good to me. I'm also seeing this issue now.

**Review by danibonilha — CHANGES_REQUESTED** [review]
Check if the avaible sections are working

**Comment by danibonilha** [comment]
Closing in favor #359 , although this fixes the crash, it doesn't properly show the merchant transactions when it should

**Comment by eshinkawa** [comment]
it was working, just tested, but your solutions cover more ground

**Pull request closed without merging**
