### PR TITLE
[CS-4506] Backup Success Screen UI

### PR DESCRIPTION
**Pull request by oidoug**
### Description

This adds a new screen for showing the backup success state.

- [x] Completes #(CS-4506)

### Checklist

- [x] Tested on a small device
- [x] Tested on iOS
- [x] Tested on Android

### Screenshots

Screenshot

Screenshot

### CODE REVIEW

**Review by danibonilha — COMMENTED** [review]
This screen has minimum differences when compared with `BackupRecoveryPhraseScreen ` is there a specific reason to not make it more generic and share the screen for both cases ? Maybe we'll need to change the name, but I was thinking the entry point to `backup` would be the same regardless of the status, and based on the status we would render the options, rather than check for backup to conditionally navigate the user. I'm not very close to this project though, so excuse me if I said something that does not make sense, please let me know.

**Comment by oidoug** [comment]
No, you are right. I was going to bring that up offline. It's very possible to use a shared template.
I'll convert this to a draft and make an attempt on extracting the UI from the recovery screen tomorrow.

**Comment by oidoug** [comment]
@danibonilha on a second thought, I believe it's cleaner if we maintain these two screen distinct.

They pretty much look the same, but there are small differences and the majority of the duped code is already extracted in reusable components.

Let's discuss this more offline.

**Comment by oidoug** [comment]
We changed course to improve the backup flow and this screen is being replaced by a more generic Recovery Screen.

**Pull request closed without merging**
