### PR TITLE
[CS-2577] Fix crash issue when press gas price

### PR DESCRIPTION
**Pull request by topwebtek7**
### Description

- [x] Completes #CS-2577

### Checklist

- [x] All UI changes have been tested on a small device

### Screenshots

Dec-03-2021 03-22-12

### CODE REVIEW

**Review by danibonilha — APPROVED** [review]
LGTM

**Comment by lukemelia** [comment]
This looks like it fixes the crash. My understanding is that we don't want to support changing gas price on xdai chain. @habdelra @kdowlin can you confirm or deny?

**Comment by habdelra** [comment]
@lukemelia confirm

**Comment by danibonilha** [comment]
@kdowlin we probably need a diff ticket to disable this on xDai, as the fix of the crash is not related with the gasPrice itself

**Comment by kdowlin** [comment]
> @kdowlin we probably need a diff ticket to disable this on xDai, as the fix of the crash is not related with the gasPrice itself

will do

**Pull request merged**
