### PR TITLE
Break up shim.js

### PR DESCRIPTION
**Pull request by lukemelia**
This file was a mish-mash of different responsibilities and an exported const that was being imported by two screens was causing a lot of surprising behavior when debugging certain modules and tests.

In the future, we could consider moving this to App.js

### CODE REVIEW

**Comment by topwebtek7** [comment]
As far as I know, shim.js is auto generated by running `yarn nodeify`..  anyway looks good if it's helpful for tests

**Comment by lukemelia** [comment]
Ah, seems like it was originally generated with the content in https://github.com/tradle/rn-nodeify/blob/master/shim.js and collected all sorts of stuff after that.

**Review by danibonilha — COMMENTED** [review]
LGTM, tested locally, everything seems to be working fine

**Comment by danibonilha** [comment]
@lukemelia   I'm sorry, I had some internet issues and wrongfully clicked on `close pull request` 😓  once the page restarted

**Review by danibonilha — APPROVED** [review]

**Pull request merged**
